### ISSUE TITLE
Not receiving incoming calls in quit state

### ISSUE THREAD

**Issue by MEsteves22** [voximplant/react-native-voximplant#156]
Hello,

I'm having a problem where I'm not able to receive incoming calls when the app is in quit state. Everything is working fine with version 1.30.0. The problem started to happen with versions 1.31.0 and 1.32.0. 

I get the following messages on the call logs after the call ends on the caller side:

`Sent event to JS onPhoneEvent with params [{code = 480 ; headers = {Reason =  ; } ; id = tTjUYtpCTTeMmvlVqWPKDeOkPY1zW0bigoVyzVdL6tA ; name = Call.Failed ; reason = User Temporarily Unavailable ; } ;  ]`

`Sent event from JS onPhoneEvent with params [{code = 480 ;  headers = {} ;  id = P5sqjP67Rh6xwMJclBAUxdC-F0VTHUudrlQKixY3wO8 ;  name = Call.Failed ;  reason = Destination number is unavailable ;  } ;  ]`

`Sent event to JS onPhoneEvent with params [{cost = 0 ; direction =  ; duration = 0 ; headers = {Reason =  ; } ; id = 95FD7420D2BCA8AE.1651055835.697740 ; internalCode = 480 ; name = Call.Disconnected ; reason = Temporarily Unavailable ; } ;  ]` 

I tested this on Android.

Thank you!

**Comment by YuliaGrigorieva** [comment]
Hello @MEsteves22 !

The logs provided show that the client has not received the push notification or has not logged in after receiving the push.

Could you please check if the push notification was sent in this call (or in a call where the issue is reproducible) by checking Call.PushSent event? Please take a look at this article for references: https://voximplant.com/docs/guides/troubleshooting/push

Regarding the SDK update, we do not see any changes that may affect push notification functionality.

If the push sending result is successful in the call session logs, could you please collect and send adb logcat logs to support@voximplant.com for further analysis.

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment]
Hello @MEsteves22 ,

Seems we have found a possible root cause of this issue, we are currently preparing a hotfix update. 

Best regards,
Yulia Grigorieva

**Comment by pe1ros** [comment]
Hello @MEsteves22 !

Thank you for reaching out to us!

We have found the root cause of the issue and have just released Voximplant React Native SDK 1.32.1 with the fix.

Please update to the new version and let us know if the issue is still reproducible.

**Comment by MEsteves22** [comment]
Hello @pe1ros @YuliaGrigorieva!

I tested the new version and everything is working as expected now.

Thank you for your help and time!
