### ISSUE TITLE
Using only for audio routing

### ISSUE THREAD

**Issue by Bayramito** [voximplant/react-native-voximplant#184]
Is there any chance to use only for audio routing ? Like get and set audio routes?

Is this possible?

**Comment by Bayramito** [comment]
> @Bayramito
> 
> Could you please provide more details regarding your question?
> 
> What do you mean by "audio routing"? Android and iOS platforms have different audio system and different API to manage audio devices. Voximplant React Native SDK provides a common API to select an audio device and monitor audio device changes such as Bluetooth headset connection/disconnection or wired devices plug/unplug.
> 
> > Using only for audio routing
> 
> Do you mean that you would like to use the SDK for audio device management without using other functionality the SDK provides?
> 
> Best regards, Yulia Grigorieva

Kind of yeah.. I wan’t to use only these 2 methods.  But selectAudioDevice is not working on Android on me? Is there any specific requirement for it?

**Comment by YuliaGrigorieva** [comment]
Hello!

There are some limitations for both platforms. You can check them in the following docs:
- android - https://voximplant.com/docs/references/androidsdk/hardware/iaudiodevicemanager
- ios - https://voximplant.com/docs/references/iossdk/hardware/viaudiomanager#selectaudiodevice

Also, it is worth noting that audio device management in the Voximplant SDKs considers a call state made using the Voximplant platform. Using Voximplant SDK API for audio routing only may result in unpredictable behavior since other SDks may make the OS trigger system events for audio subsystem and these events may be handled incorrectly due to a different call state in the Voximplant SDK and other SDK.

Best regards,
Yulia Grigorieva
