### ISSUE TITLE
when app goes in background SDK getting disconnected.

### ISSUE THREAD

**Issue by anishtr4** [voximplant/react-native-voximplant#32]
@YuliaGrigorieva,  Hi Yulia , When the app goes to background the  SDK getting disconnected. Is there any way to prevent this ?

**Comment by YuliaGrigorieva** [comment]
Hello!

Could you please provide more details:
1. what platform (android/ios) do you observe this issue on
2. is there a call when the SDK is disconnecting

Best regards,
Yulia Grigorieva

**Comment by anishtr4** [comment]
@YuliaGrigorieva  , 

1 ) I have faced this issue in IOS. I belive this issue is there in android as weel. Is there any extra step we need to take to prevent this. ?
2) The disconnect event listener is getting fired and getting the

**Comment by YuliaGrigorieva** [comment]
Hello!

Since iOS 10 Apple changed the policy for background connections, so it is not possible to maintain the connection to the Voximplant Cloud in the background if there is no active calls at the moment.
The best practices to support incoming calls when application is in background is to use push notifications (PushKit). Please take a look at our demo project that has PushKit integrated.

In case you face the issue the call is disconnected in the background, please check that you have declared the following Background modes in your xcode project:
    Audio and AirPlay
    Background fetch
    Remote notifications
    Voice over IP
These background modes should prevent a VoIP call to be disconnected when app is going to the background.

Best regards,
Yulia Grigorieva

**Comment by gurkanbulut** [comment]
Pls help ASAP , Right now I have exactly the same issue , i checked all of these which is in the comment but everything is the same , can you help me to solve this problem ?
