### ISSUE TITLE
Camera permission on Android

### ISSUE THREAD

**Issue by skeet** [voximplant/react-native-voximplant#35]
Is there any way to disable asking for the camera permission on Android?

We've tried passing false as the first parameter of `init()` which disables the video but crashes the app as the permission is still required.

I'm building an app that only uses voice and cannot have the camera permission.

Thanks.

**Comment by YuliaGrigorieva** [comment]
Hello!

VoxImplant.SDK.init() method has only one parameter that is a map: 
https://github.com/voximplant/react-native-voximplant/blob/8d245e06595ebdfd52554c37698b21421255fb06/index.js#L446-L455

The correct usage is the following:
```
const options = {
  enableVideo: false,
};
VoxImplant.SDK.init(options);
```

Please try this way and let us know if the issue is resolved.

Best regards,
Yulia Grigorieva

**Comment by skeet** [comment]
Thank you - this fixed our issue!
