### ISSUE TITLE
Native module cannot be null.

### ISSUE THREAD

**Issue by ricsam** [voximplant/react-native-voximplant#42]
![image](https://user-images.githubusercontent.com/986386/42724451-a633a664-8772-11e8-8a3e-15e5e31d76c1.png)

On iOS when running:
```
import { Voximplant } from 'react-native-voximplant';
const voxClient = Voximplant.getInstance({
  enableVideo: false,
  saveLogsToFile: false,
});
```

I've followed the steps in README.md

**Comment by YuliaGrigorieva** [comment]
Hello!

It seems that you have not added react-native-voximplant to your project's Podfile.
Please ensure that:
1. you have this line in your Podfile: 
https://github.com/voximplant/react-native-demo/blob/568da381ab0725bda7a15f6f57a6ce3bdcc1f118/ios/Podfile#L79
2. "pod install" command succeeded

Best regards,
Yulia Grigorieva

**Comment by ricsam** [comment]
Hi @YuliaGrigorieva! I have that exact line in my podfile and I can successfully build the project for iOS:
<img src="https://user-images.githubusercontent.com/986386/42756914-5d08b05a-88fe-11e8-9d6b-ea295d9e26d6.png" height="800" />

So something else is wrong, do I need to enable something more in xcode? e.g. notifications etc for the SDK to be able to run? I am using React native version 0.56.0.

The SDK works for me on Android.

Thanks!

**Comment by YuliaGrigorieva** [comment]
Hello!

I was able to reproduce your issue on a project created from scratch with RN 0.56 only if react-native-voximplant is not included to the Podfile.

Generally this error means that native modules of react-native-voximplant are not compiled/linked correctly.

Could you please check that you have build logs for react-native-voximplant framework like this?

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/8545374/42762530-446805d0-8919-11e8-88d0-4d91057b8b49.png">

Do you have a possibility to provide me a sample project on which I could reproduce the issue?

Best regards,
Yulia Grigorieva

**Comment by ricsam** [comment]
@YuliaGrigorieva Thanks for the response! I've created a sample project which gives me the same result: https://github.com/ricsam/testVI
I provided screenshots of my project, build logs and run errors.

Observe that I have not removed anything from the "Libraries" folder in the xcode project. If I remove the *.xcodeproj from "Libraries" the build fails.

**Comment by YuliaGrigorieva** [comment]
Hello!

It seems to be the root cause of the issue. You should remove all *.xcodeproj from Libraries section because otherwise React is compiled and linked twice (as a framework and as a static library). You can see that RCT classes are located in 2 different locations in your screenshots from the Xcode output.

I have forked your repository and made a commit with the fix. Please take a look: https://github.com/YuliaGrigorieva/testVI

To summarise my changes:
1. You don't need 'cocoapods-fix-react-native' plugin for RN 0.56. All previous issues in the react-native were fixed. If you take a look at 'cocoapods-fix-react-native' git history, you can see that they have removed all changes for RN 0.56: https://github.com/orta/cocoapods-fix-react-native/commits/master
2. You may face with `'RCTAnimation/RCTValueAnimatedNode.h' file not found` error while building. It can be fixed by adding postintall script in package.json: https://github.com/voximplant/react-native-demo/blob/c6058e6a1635a9123a550ad70bc2e9b32b071a1a/package.json#L7
3. I have commented out all code in the tests. To resolve compile issues in the tests, it is required to add react dependencies to test target in Podfile.

Please let me know if the issue is resolved on your side.

Best regards,
Yulia Grigorieva

**Comment by ricsam** [comment]
Absolutely amazing, thanks a million! Your forked version worked perfectly! 🎉

**Comment by ozanmanav** [comment]
I have a same problem. I tried these things but i'm getting this error.

Is there any idea for this ?
