### ISSUE TITLE
Is your package only compatible with apps that were created using `react-native init`?

### ISSUE THREAD

**Issue by Billmike** [voximplant/react-native-voximplant#50]
In the docs for this package, it was specifically stated that it should be installed with apps created using `react-native init`. How about apps created using `create-react-native` cli? Is that supported also?

**Comment by YuliaGrigorieva** [comment]
Hello!

`create-react-native-app` command creates a react-native application with only Javascript part. 

Our sdk uses native modules, that's why the application should be created with `react-native init` command. This way the application will be created with required structure, i.e. `android` and `ios` directories with minimum required setup.

In case if the application was created with `create-react-native-app` command, you will need to add the support for native modules. Please check "Building Projects with Native Code" section: https://facebook.github.io/react-native/docs/getting-started

Best regards,
Yulia Grigorieva
