### ISSUE TITLE
Cannot find symbol "..RequestAudioFocusMode" on Android

### ISSUE THREAD

**Issue by firehand33** [voximplant/react-native-voximplant#51]
i getting the following error when building on Android after upgrading the package to version 1.3.1.

> /node_modules/react-native-voximplant/android/src/main/java/com/voximplant/reactnative/Utils.java:12: error: cannot find s
> ymbol
> import com.voximplant.sdk.client.RequestAudioFocusMode;
>                                 ^
>   symbol:   class RequestAudioFocusMode
>   location: package com.voximplant.sdk.client
> /Users/gobunny/Workspace/Backup/GoBunnyGirls/node_modules/react-native-voximplant/android/src/main/java/com/voximplant/reactnative/Utils.java:151: error: cannot findsymbol
>         static RequestAudioFocusMode convertStringToRequestAudioFocusMode(String requestAudioFocusMode) {
>                ^
>   symbol:   class RequestAudioFocusMode
>   location: class Utils
> /Users/gobunny/Workspace/Backup/GoBunnyGirls/node_modules/react-native-voximplant/android/src/main/java/com/voximplant/reactnative/Utils.java:154: error: cannot findsymbol
>                                 return RequestAudioFocusMode.REQUEST_ON_CALL_CONNECTED;
>                                        ^
>   symbol:   variable RequestAudioFocusMode
>   location: class Utils
> /Users/gobunny/Workspace/Backup/GoBunnyGirls/node_modules/react-native-voximplant/android/src/main/java/com/voximplant/reactnative/Utils.java:157: error: cannot findsymbol
>                                 return RequestAudioFocusMode.REQUEST_ON_CALL_START;
>                                        ^
>   symbol:   variable RequestAudioFocusMode
>   location: class Utils
> /Users/gobunny/Workspace/Backup/GoBunnyGirls/node_modules/react-native-voximplant/android/src/main/java/com/voximplant/reactnative/VIClientModule.java:71: error: cannot find symbol
>                 config.requestAudioFocusMode = Utils.convertStringToRequestAudioFocusMode(requestAudioFocusMode);
>                       ^
>   symbol:   variable requestAudioFocusMode
>   location: variable config of type ClientConfig
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 5 errors

**Packages Version**
"react-native": "^0.57.7",
"react-native-voximplant": "^1.3.1",

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reporting the issue!

RequestAudioFocusMode java enum is a part of Voximplant Android SDK 2.8.0 version to which the React Native SDK native android module is updated to.

The issue may be caused by gradle sync fail.

Unfortunately, we can't reproduce the issue with our demo project. Have you tried to build the [demo project](https://github.com/voximplant/react-native-demo)? Do you observe the issue with demo project?

Could you please try to clean your project (android build folders as well) and try to build it again? 

Please let me know the results.

Best regards,
Yulia Grigorieva
