### ISSUE TITLE
AVAudioSessionCategoryAmbient is not working properly in iOS

### ISSUE THREAD

**Issue by giodss** [voximplant/react-native-voximplant#52]
Hi, I have been trying to get my iTunes keep working by implementing AVAudioSessionCategoryAmbient so that the music will still play while opening the app, but it seems to be conflicted with codes in VoxImplant, resulting the music to be stopped whenever I open the app. 

Here's my version of react-native and voximplant:
"react-native-voximplant": "1.0.1"
"react-native": "^0.55.3",

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for your report!

The issue should be fixed in later Voximplant React Native SDK versions. I recommend you update the SDK to 1.3.1 version. 
With this update, you don't need to set AVAudioSessionCategoryAmbient, SDK will manage audio session categories itself.

Please let me know if the issue is reproducible with SDK update.

Best regards,
Yulia Grigorieva

**Comment by giodss** [comment]
Hi Yulia, thanks for the fast response.

I have tried to update the SDK, and it is now working as expected, so many thanks for the assistance!
