### ISSUE TITLE
How do I access SIP headers passed using `extraHeaders` when receiving a call

### ISSUE THREAD

**Issue by sanjaypojo** [voximplant/react-native-voximplant#80]
When I make an outgoing call, I pass an extra SIP header containing some call details. How do I access this when receiving a call? The `headers` object does not contain the extra header I passed. This is what I passed to `extraHeaders`:
```
{ "X-RUNE-ABC": "5"}
```
When I receive the incoming call, I only have the following items in the object:
```
{
  VI-Browser: "voxmobile",
  VI-Client-IP: "18.85.25.61",
  VI-ClientVersion: "android-2.11.1_react-1.6.0",
  X-DirectCall: "true"
}
```

**Comment by YuliaGrigorieva** [comment]
Hello @sanjaypojo ,

The issue may be related to your VoxEngine scenario. 
If you use `VoxEngine.forwardCallToUserDirect` scenario, you need to change it to the following one:
```
VoxEngine.addEventListener(AppEvents.CallAlerting, (e) => {
  const newCall = VoxEngine.callUserDirect(
    e.call, 
    e.destination,
    e.callerid,
    e.displayName,
    e.headers
  );
  VoxEngine.easyProcess(e.call, newCall, ()=>{}, true);
});
```

Please let me know if you need an example for a different scenario or you have any questions. Please also let me know if the issue is resolved by changing the VoxEngine scenario.

Best regards,
Yulia Grigorieva

**Comment by sanjaypojo** [comment]
Thanks @YuliaGrigorieva, this looks great, I'll try it out!

**Comment by sanjaypojo** [comment]
This is working for us, thanks @YuliaGrigorieva 👍
