### ISSUE TITLE
How do I login into your application. 

### ISSUE THREAD

**Issue by abhagsain** [voximplant/react-native-voximplant#85]
I can't seem to find out how do I log into your application. I've tried my voximplant username & password and also as a registered user of my application for eg. user@myapplicationname.voximplant.com but it's saying Invalid username.

**Comment by YuliaGrigorieva** [comment]
Hello @abhagsain ,

I suppose this issue is related to login to our demo application: https://github.com/voximplant/react-native-demo
In such a case you need to input your Voximplant user (previously created in the Voximplant Control Panel) in the following format: `username@application.account`.
The demo application will add ".voximplant.com" to your input.

However please consider that adding ".voximplant.com" to the user name input is implemented on the demo application side only to simplify the input on mobile devices. If you use Voximplant React Native SDK API you need to provide full Voximplant user name to the login method. See Voximplant React Native SDK [API references](https://voximplant.com/docs/references/reactnative/voximplant/client#login).

Please let me know if the issue is resolved.

Best regards,
Yulia Grigorieva

**Comment by abhagsain** [comment]
> @application.account

Still saying invalid username. Can you please give me an example?

**Comment by YuliaGrigorieva** [comment]
Hello @abhagsain ,

Have you registered a Voximplant developer account and created Voximplant application of users in https://manage.voximplant.com/auth/ ?

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment]
Please take a look at this tutorial (Users section): https://voximplant.com/docs/references/articles/quickstart/apps-scenarios-rules-and-users

After you have created users for your Voximplant application, you can login with their credentials. You need to enter:

- `user@app.account` as the login
where
"user" - the username of the user you have created
"app" - Voximplant application name that you have created
"account" - your Voximplant account name
- password that you have indicated while the user creation

Best regards,
Yulia Grigorieva

**Comment by reactdevrocks** [comment]
@YuliaGrigorieva i have given the info above yet i can not logged in.

**Comment by YuliaGrigorieva** [comment]
Hello @reactdevrocks ,

Please take a look at the screenshot provided in [this comment](https://github.com/voximplant/react-native-demo/issues/16#issuecomment-510866009) and align your input data.

Best regards,
Yulia Grigorieva

**Comment by reactdevrocks** [comment]
Thanks it worked. Now i have installed this demo in two ios devices but when i call (audio/video) then in another nothing is coming means i am not getting any call. please help me for that issue.

**Comment by YuliaGrigorieva** [comment]
Hello @reactdevrocks ,

Please fill a different issue in [react-native-demo](https://github.com/voximplant/react-native-demo) project or contact us at support@voximplant.com

Best regards,
Yulia Grigorieva
